# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad13316f387a718f7ddc5807c14f66ee3058d8adfd1e68b891354925ebb05f918d7a1b181fd652a5a143650d23796393f8f132ab6a29ec67224d189061ca83c9

test:
  secret_key_base: f6ed2e10f2ea8b58126b75c81db7ed992c6ce04d702fae3daf22b66633061789e6fb1183bed268fedd8a483ff964798dc97786d4db48c6d81cdadd65bbabecc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
